### ISSUE TITLE
Pineapple on Pizza: Yay or nay? 

### ISSUE THREAD

**Issue by tysmithnet** [shanselman/ama#1]

**Comment by shanselman** [comment]
Yes. LOTS OF IT AND I AM NOT ASHAMED TO SAY IT. 

I am pro-pineapple in ALL forms. It makes everything better.

**Comment by jerriep** [comment]
>  It makes everything better

I respectfully disagree 😉  Living in Thailand, one of my favourite dishes is [Chicken with cashew nuts](https://www.google.com.mx/search?q=chicken+cashew&oq=chicken+cashew&aqs=chrome..69i57j0l5.3703j0j1&sourceid=chrome&ie=UTF-8). Currently I am traveling in Mexico, and yesterday I saw a Thai restaurant, and popped in to order my favourite. 

Strangely they added pineapples to it. It did not make it better 😞 

I am however a big fine of pineapple with most other things - especially pizza 😄
