### ISSUE TITLE
Recommendation for transferring from device-bound developer (desktop/mobile) to the web world?

### ISSUE THREAD

**Issue by Code-ScottLe** [shanselman/ama#10]
I started off with WPF, stuck with it and now UWP, but now wanting to move toward the web (due to recent endeavors with certain team within MSFT that left me a huge desire to learn more about the web). What is your recommendation for this transition to go smother? (I'm starting with ASP.NET Core right now)

**Comment by shanselman** [comment]
Maybe look at React/ReactNative, Ionic, Typescript, Angular, as possible bridges. If you are an MVVM person, perhaps explore web-based MVVM frameworks that will make it more familiar with databinding features, etc.

**Comment by ampslive** [comment]
Hey @Code-ScottLe  ...  If I may add my two cents... Start with learning MVC and ASP.NET Core. Most desktop apps would be MVVM so MVC will be a good shift. 
For the 'V' in MVC - Start with HTML, CSS and JavaScript. Post this you can looking at React/Angular/Typescript
