### ISSUE TITLE
Where should I start if I want to restart my career in software development?

### ISSUE THREAD

**Issue by neelmallepally** [shanselman/ama#101]
I learned asp.net web forms (some Javascript, CSS & T -SQL) to get a job after graduating from electrical engineering and have been working only in that technology for last 7 years. I think I'm outdated. If I have to restart/add other tech to my career in software development, can you suggest a learning path (like must know concepts for a software developer). Thank you.

**Comment by shanselman** [comment]
This is what I tell people: http://www.hanselman.com/blog/IfYouHadToStartOverWhatTechnologiesWouldYouLearnIn2014.aspx

Update to ASP.NET MVC or ASP.NET Core 2.0 and learn some new Javascript

**Comment by neelmallepally** [comment]
Perfect. Lesson learned: Always search @shanselman's blog before you ask AMA question.
