### ISSUE TITLE
What do you think about buying a Surface Pro 4?

### ISSUE THREAD

**Issue by ampslive** [shanselman/ama#103]
I always wanted to own a Surface device and now currently see a deal for Surface Pro 4 i5 8GB RAM with Keyboard for $999.

In your opinion would you recommend a Surface Pro 4 i5 8GB as a development machine? I predominantly develop for ASP.NET and occasionally dabble in Xamarin. 
I need something ultraportable, touch, pen, etc around the $1000 budget.

**Comment by shanselman** [comment]
Does that include the type keyboard? Seems a great deal. One of my surfaces is an SP3 and it runs VS fine.

**Comment by ampslive** [comment]
Yes it has the black type cover keyboard

**Comment by jnm2** [comment]
I love the SP3 and SP4, both quite adequate for development, but I've only used i7s.
