### ISSUE TITLE
Age of empires modding 

### ISSUE THREAD

**Issue by M-Zuber** [shanselman/ama#105]
In your answer to the question on gaming, I saw that in your list was AoE 2 & 3
Curious if you ever did anything like a full on mod or even just a custom campaign with triggers ect within the tools provided by the game

**Comment by shanselman** [comment]
I haven't personally done any modding but I did have the main modding company on my podcast https://www.hanselminutes.com/568/forgotten-empires-amazing-games-age-of-empires-is-back-with-bert-beeckman
