### ISSUE TITLE
How do you level out your own self-expectations?

### ISSUE THREAD

**Issue by snickler** [shanselman/ama#108]
Hi Scott!

I've been wondering how you're able to level out your own self-expectations. I have the tendency to feel like I need to be at a specific point with my knowledge and experience, while usually feeling like what I'm doing is not enough. Is there a way to slow down someone who wants to go 0-100 every time?

Thanks!

**Comment by shanselman** [comment]
Man, I dunno. I look at other people out there (although often I'm comparing myself to people who don't have any life-stuff (kids, whatever) taking up their time) doing the most and I think I'm not doing the most. I have no answer for you. I need to learn Go, I need to learn Kubernetes, I need to up my Docker abilities, but I also want to hang out with my kids.
