### ISSUE TITLE
Which graphic novel impacted you the most?

### ISSUE THREAD

**Issue by shadyendless** [shanselman/ama#11]
I saw you mention graphic novels during the #shelfie spree, so I was wondering which graphic novel (individual or series) you've read that impacted you the most (emotionally, through-provokingly, etc).

**Comment by shanselman** [comment]
* Y the Last Man was fantastic
* Preacher is excellent
* The Walking Dead (I read them before they were a thing)
* Saga
* Miss Marvel - Kamala Khan
* Moon Girl and Devil Dinosaur
