### ISSUE TITLE
Solar Eclipse viewing in Oregon

### ISSUE THREAD

**Issue by pbolduc** [shanselman/ama#110]
My family is travelling down next week from Vancouver, BC to Portland to view the solar eclipse on the 21st.  I know the 100% eclipse viewing will be had in Salem and south of Salem.  We plan to head from Portalnd to Salem on the morning of the 21st.  Are you able to suggest any places that may be good viewing locations?  We have young kids so a park with a play ground may be useful as well.  Any suggestions are welcome.  It would be better to get a local's suggestions vs asking Google/Bing maps.

**Comment by shanselman** [comment]
This is one of the best parts, further north, in McMinnville. Great for little ones http://www.mcminnvilleoregon.gov/parksrec/page/joe-dancer-park

I'm hearing traffic will be nuts that morning so DO mentally prepare yourself and your family that you might end up seeing it from the car, while on I5. Really. And let me know how it goes.

It would be better to go down the night before and sleep in a park http://www.kgw.com/news/eclipse/salem-expecting-125000-visitors-for-eclipse/460889077
