### ISSUE TITLE
Best way to communicate with SO you don't live with? (without constantly interrupting work)

### ISSUE THREAD

**Issue by partounian** [shanselman/ama#116]
My SO seems to text me a lot, and it's understandable that we should have good communication, but it interrupts my work often. Any ideas for staying in communication without interrupting work?

**Comment by shanselman** [comment]
I use Airplane Mode while on the ground. I let them know that I work in sprints, so I'll be "offline" for 2-3 hours at a time. You can start at 1 hour and work your way up.

**Comment by jnm2** [comment]
When I'm using the Pomodoro technique, I'll silence my phone and respond during breaks.
(I want to be reachable by call for emergencies.)
