### ISSUE TITLE
What are your thoughts on .NET on Linux and Dockerization?

### ISSUE THREAD

**Issue by bbatchelder** [shanselman/ama#13]
Is this the way forward?  Or is it a fad?  Something even small web apps should do, or only large/enterprisey apps?

**Comment by shanselman** [comment]
I think any app that needs to scale out (n times) will probably be in SOME kind of container in the next year or two. Docker, something. I think that Docker will become FTP for code, where once Git was FTP for code. Docker will be how you deploy sites, even little ones.
