### ISSUE TITLE
What's your every day carry (EDC) when you leave the house?

### ISSUE THREAD

**Issue by mrxinu** [shanselman/ama#14]

**Comment by shanselman** [comment]
* Metronic Insulin Pump
* [RileyLink RF/BT Bridge](https://www.hanselman.com/blog/ThePromisingStateOfDiabetesTechnologyIn2016.aspx)
* Dexcom G5 Continuous Glucose System
* iPhone 6s+, ID, credit cards
* Walking around money ($100?)
