### ISSUE TITLE
How do you have so much energy to do all the side projects you do?

### ISSUE THREAD

**Issue by wiltaylor** [shanselman/ama#17]
How do you have so much energy to constantly do all the community stuff with work, being a parent and all the side projects you always have on the go. 

I am always in awe of how much energy you seem to have.

**Comment by shanselman** [comment]
Thanks for the compliment. Usually I try to find finite but possible stuff to do, and often I include my kids. Having kids (neighborhood kids, your own kids, random kids from schools) around can help motivate as well. Sometimes there are classes that can be taught or videos that can be made from a single project. Mostly the project is the energy. If it’s fun and interesting it will finish itself. If it’s hard (like working out) or boring (like writing books) then I have trouble.
