### ISSUE TITLE
I am electrical engineer turned to programmer. I have been programming in .net for 12 years. .Net made my life so easy that I don't know algorithms. Is it necessary that I should learn?

### ISSUE THREAD

**Issue by fayaz93** [shanselman/ama#24]

**Comment by shanselman** [comment]
Check out @robconery’s “Imposter’s Handbook.” That excellent book will give you 80% of the algo info you need and you can google the rest. It doesn’t hurt to study up a little.

**Comment by robconery** [comment]
I've upped the algorithms chapter and buffed out the data structures too :). I think I covered the ones needed for an interview.

Also: thanks Scott for the link!
