### ISSUE TITLE
Will there ever be a .Net event in Vietnam?

### ISSUE THREAD

**Issue by thuannguy** [shanselman/ama#27]
I saw you guys have awesome events in all the ""big" countries every year. Do you happen to know will there ever be one in Vietnam? We are an emerging market, but there are plenty of good .Net developers here :)

**Comment by shanselman** [comment]
Do you have some people at the local Microsoft office you want to hook me up with? What is the biggest Vietnamese event?

**Comment by thuannguy** [comment]
FYI: I'm trying to get some contacts :) Not the easiest thing do to with MS VN though :)

**Comment by thuannguy** [comment]
Hi,
I managed to exchange some messages with a guy from MS VN. He said that there is no concrete plan for a big event that he can invite famous speakers. Maybe somewhere in the future.
We are lacking of good .NET events here. The biggest Vietnamese event in Ho Chi Minh city (which is the largest city in VN) is (BarCamp)[https://en.wikipedia.org/wiki/BarCamp]:
https://www.facebook.com/BarCampSaigon/posts/10154791709192754. It doesn't focus in tech or programming, but a majority of topics are tech-related. 

Thank you for reading :)
Thuan.
