### ISSUE TITLE
Can you hook me up with a certificate to Angle Brackets in Las Vegas this Fall?

### ISSUE THREAD

**Issue by psmak4** [shanselman/ama#28]
I'll buy you dinner some night while there. =)

**Comment by shanselman** [comment]
Like a free ticket?

**Comment by psmak4** [comment]
Yep. I figured it couldn't hurt to ask.

Here was my highlight from the Angle Brackets in May: [https://twitter.com/ThePrestonJones/status/867010435538718720](https://twitter.com/ThePrestonJones/status/867010435538718720)
