### ISSUE TITLE
A comedy of errors

### ISSUE THREAD

**Issue by wazzamatazz** [shanselman/ama#35]
Have you ever considered revising your obviously incorrect opinion that Big Bang Theory is better than The IT Crowd? It would probably help with all those people who say things on Twitter like, "I followed @shanselman the technologist, not the mistaken comedy critic".

**Comment by shanselman** [comment]
When did I say that? They are very different and both classics. Given I look somewhat like Chris O'Dowd, I'm happy to revise that opinion.

**Comment by wazzamatazz** [comment]
I remember you tweeting something like, "Sorry UK folks, but Big Bang Theory > IT Crowd" a few years ago. I was horrified. HORRIFIED!

**Comment by jnm2** [comment]
https://twitter.com/shanselman/status/24741868784848896 (6.5 yrs ago)
https://twitter.com/shanselman/status/2927711582 (8 yrs ago)
(Via https://twitter.com/search?f=tweets&q=%40shanselman%20big%20bang%20theory%20it%20crowd&src=typd)

@wazzamatazz sure has a memory lol!

**Comment by jnm2** [comment]
https://twitter.com/shanselman/status/2927711582

**Comment by jnm2** [comment]
@wazzamatazz sure has a memory!

**Comment by shanselman** [comment]
SCANDALOUS. I must apologize. WHAT WAS I THINKING?!?

**Comment by shanselman** [comment]
https://twitter.com/shanselman/status/894994415315410944
