### ISSUE TITLE
What advice would you give an undergraduate looking to get a job

### ISSUE THREAD

**Issue by Kethku** [shanselman/ama#37]

**Comment by shanselman** [comment]
Look for opportunities to get your portfolio or Github looked at. Both Stephanie Hurlbut (@sehurlburt on twitter) have offered to RT jr engineer Github and resumes on Twitter to try to get more eyeballs on them. Find a mentor. Go to meetups. SPEAK at meetups. Network. 

Also, check out my 2 hour free movie http://www.getinvolvedintech.com
