### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by cheers00** [shanselman/ama#39]
You used to blog about development tools but you have stopped doing it. Your last blog on tools was 
https://www.hanselman.com/blog/ScottHanselmans2014UltimateDeveloperAndPowerUsersToolListForWindows.aspx

Any plans to write a blog about tools? Or you just use vscode for everything.

Thanks

**Comment by shanselman** [comment]
It takes a LOT of time to update that tools list, and most/many tools have gone to the web. I will try to update it though, soon.
