### ISSUE TITLE
How much would it cost to invite you to give talks to my local conference?

### ISSUE THREAD

**Issue by FaridAhamat** [shanselman/ama#45]
And how do I do that, do I have to send email to your boss? Would you be okay to if I invite you to give talk live via Skype? Do I have to pay you?

**Comment by shanselman** [comment]
I don’t usually charge for giving talks unless I am doing it on my own time/on the side, or for a large corporation. I talk at user groups for free or very little. I ask only for T&E (Travel and Expenses). The bigger issue is the time away from family and work. If I am near your country or passing through, that’s better.
