### ISSUE TITLE
What Visual Studio Extensions do you / your team use?

### ISSUE THREAD

**Issue by florianwachs** [shanselman/ama#50]
Thanks for the AMA! Great Idea. I´m wondering which Visual Studio Extensions you / the asp.net team uses for daily work. For example, do you use Resharper?

Thanks!

**Comment by mrxinu** [comment]
He did in 2014 - it was on his list of must-haves. I can't imagine he would have stopped. ReSharper is the cat's meow.

https://www.hanselman.com/blog/ScottHanselmans2014UltimateDeveloperAndPowerUsersToolListForWindows.aspx

**Comment by florianwachs** [comment]
Thank you @mrxinu!
