### ISSUE TITLE
How will you handle the "N" word if your kids will use it?

### ISSUE THREAD

**Issue by saberone** [shanselman/ama#53]
First let me quickly describe what my background is. I'm born in Holland which makes me Dutch, and my parents come from Tunisia (Northern Africa) which makes me Tunisian too. But the relevant thing for this question is that I'm Black and married to my white Dutch wife. We got three boys, and as you'd expect they're lighter skinned than I am. My youngest one would could even be considered to be white. And a few years ago I even understood that the Black people above the Sahara aren't even N's in the first place.

Anyways. I use the N word among friends a lot of times. And over here in Holland it doesn't have the same "ring" to it as in the States , although the Dutch didn't exactly behave very well when it comes to Black people in the past, white people sometimes use the N word over here. But a while ago I was thinking what should I do if one of my kids decides to use the word. Are they even considering themselves to be Black, should I even tell them. And if I don't would that make me "fake". And how on earth am I even going to enjoy Hip-Hop without being proud to be Black.

Anyway. Since you also have boys and you're married to your Black wife. How do you look at the N word? I know in the States it's very relevant these days. I recon you banish the word from your house. But eventually they'll grow up and have friends, you can't control everything

**Comment by shanselman** [comment]
It’s complex. Read about the history of the word and I suspect you’ll stop using it. Your blackness isn’t defined by this word, hard-r or soft. I will encourage my kids to educate themselves and use words that mirror their thinking. If they think appropriately, they won’t need to use the word. https://www.tolerance.org/magazine/fall-2011/straight-talk-about-the-nword
