### ISSUE TITLE
Do you have a favorite quote/tenet currently (or 2 or 3)?

### ISSUE THREAD

**Issue by mrxinu** [shanselman/ama#6]

**Comment by shanselman** [comment]
"Don't give negativity a permalink." - Me
"You can only become truly accomplished at something you love. Don’t make money your goal. Instead, pursue the things you love doing, and then do them so well that people can’t take their eyes off you." - Maya Angelou
"The best revenge is your paper" - Beyonce
"God, make me so uncomfortable that I will do the very thing I fear." - Ruby Dee
"You must be the change you want to see in the world." - Maybe Ghandi, might be fake
"You can't trust quotes on the internet." - Abe Lincoln

**Comment by whoiskevinrich** [comment]
![Lincoln Quote](http://www.lolriot.com/wp-content/uploads/2011/11/Trouble-with-quotes.jpg)
