### ISSUE TITLE
Does Microsoft take care of you?

### ISSUE THREAD

**Issue by IEvangelist** [shanselman/ama#65]
You are one of the most influential faces of the developer community. You are arguably the world's most active and social developers out there. You literally do it all, [leading by example](https://github.com/shanselman), from [public speaking](https://hanselman.com/speaking) (in a huge way), [active blogging](https://hanselman.com/blog/) (way more than most), run [multiple podcasts](https://www.hanselman.com/podcasts/) (hosting some of the most interesting guests and topics), and [motivate so many of us](https://www.hanselman.com/blog/ImAPhonyAreYou.aspx) in the dev community.

> BTW, thank you for all that you have done and continue to do.

**How could Microsoft possibly compensate you enough?!**

**Comment by shanselman** [comment]
I think that I am fairly compensated. I'm not a career climber - I prefer to spend time with my family - so I am squarely "middle management." I'm not a VP or close to a VP (nearest is 3? people away) so I'm not rolling in dough, but I can say that I have food security and I can buy a new iPhone every two years.
