### ISSUE TITLE
Your Time Management

### ISSUE THREAD

**Issue by wakhidnusa** [shanselman/ama#69]
Hi,

I want to ask, how u can manage your time for work, blogging, speaking, your hobbies and your family ?

And how u get your focus on your activity ? Dou you have any tips for me ?

I asked the question because I was very weak in time management and it was difficult to focus on what I was doing.

Sorry for my bad english.

Thank you.

**Comment by shanselman** [comment]
Here are some ideas for you https://www.hanselman.com/blog/ScottHanselmansCompleteListOfProductivityTips.aspx also google "Hanselman Productivity Tips" for some videos.
