### ISSUE TITLE
What would you say to an aspiring, ambitious developer looking to become a great lead software engineer?

### ISSUE THREAD

**Issue by LarsWesselius** [shanselman/ama#71]
I'm 26 and am reasonably well on my way to do what I want to be doing - the ultimate balance between programming and people management; lead software engineer in a team of 5-6 people, creating innovative software.

**What would your advice be to get there; in your opinion what do I need to be wary of, which skills should I acquire and how do I become a better programmer?**

**Comment by ghuntley** [comment]
* Maintain a major open-source project (we are always looking for people to help out) it will stretch and grow you. See https://youtu.be/uEq-rivegew and if you want to get involved with https://reactiveui.net let me know.
* Start doing 1:1's with your manager and your peers. Listen & study the entire series of podcasts by Managertools. Start with https://www.manager-tools.com/2005/07/the-single-most-effective-management-tool-part-1 
* Internalize this https://charity.wtf/2017/05/11/the-engineer-manager-pendulum/
* Have a side-hustle/a startup and fail. You'll learn quickly to respect the other dark arts like sales (do some cold calling, learn how to _really_ handle uncertainty and rejection :p) 
* Sign up to http://softwareleadweekly.com/
* Drop technology for a bit, swing the pendulum over to managing people (interview, promotions, probations, firing, forming/norming/storming)
* Join a team where you are _the worst technologist_ and your job is to _serve the needs of the team_ (be the servant leader/janitor) - **resist the urge to do technology or pickup technology stories** do schlep work for the team instead.

**Comment by shanselman** [comment]
@ghuntley said it better than I could. I would add, be patience, be kind, and listen.
