### ISSUE TITLE
What is your current hardware setup and softwares you use daily?

### ISSUE THREAD

**Issue by sunzoje** [shanselman/ama#8]

**Comment by shanselman** [comment]
### Hardware

* I have a SurfaceBook i7 512g SSD, 16 gigs RAM, with a SurfaceDock and a $20 1080p monitor I got at Goodwill. There's a standing desk and an Anker vertical mouse
* I have a MacBook Pro for maccy stuff
* I have a desktop i7 (8 years old, original i7) with 24 gigs of RAM, 512g Samsung SSD, and 3 monitors, 1 30" and 2 24" on an NVidia 1070.

### Software

* Windows 10 Pro, Insiders Fast
* VS Code
* VS Community
* Chrome
* Teams
* Git
* WhatsApp for Windows
* Spotify

**Comment by bdwakefield** [comment]
Surely you have access to the other SKUs of VS. Why do you stick with Community?

**Comment by shanselman** [comment]
@bdwakefield Because it's free for Open Source and small businesses, and since I work in open source and want to promote small businesses and startups, I want to use the same SKU they are using.
