### ISSUE TITLE
Why is IE so horrible?

### ISSUE THREAD

**Issue by tawani** [shanselman/ama#86]
Was IE and Edge designed specifically to be that horrible?
Why can't I just right-click and clear the browser cache? Inspect? etc!!!

**Comment by jnm2** [comment]
IE and edge both have right click > inspect, and no major browser has right click > clear cache that I know of...

**Comment by tawani** [comment]
No. It doesn't work.

**Comment by anaisbetts** [comment]
u learned a cool trick today:

![image](https://user-images.githubusercontent.com/1396/29090560-c34d44e8-7c34-11e7-9451-75729977ffb0.png)

**Comment by jnm2** [comment]
> > IE and edge both have right click > inspect
> 
> No. It doesn't work.

Works on my machine™ 😄

**Comment by jnm2** [comment]
@paulcbetts Thanks! Ctrl+Shift+R is easier than Ctrl+F5, gonna switch.

**Comment by tawani** [comment]
That is not IE nor Edge


​

**Comment by jnm2** [comment]
Dude, did you even try it? I did before I spoke:

![image](https://user-images.githubusercontent.com/8040367/29092827-9ef1dd90-7c55-11e7-93d0-54074d9e0a09.png)

![image](https://user-images.githubusercontent.com/8040367/29092882-d7bfc2a4-7c55-11e7-910c-0934290d8bdc.png)

**Comment by tawani** [comment]
"Inspect Element" is not consistent. Right-Click and Clear Cache is not
present. Your first screen shot is from Chrome.

Thanks!

**Comment by jnm2** [comment]
@tawani The first screenshot was not me.

**Comment by tawani** [comment]
@jnm2 Just noticed. thx!
