### ISSUE TITLE
On video games and VR/AR

### ISSUE THREAD

**Issue by DanAtkinson** [shanselman/ama#90]
This is more of an off-the-clock question.

* Do you get to play games much?
* Do you prefer PC, console, or phone/tablet games?
* Do you play games with the family or by yourself?
* Do you have a VR headset? More than one? Hololens perhaps?

I'd also love to know your thoughts with regards VR/AR in general. Not specifically Rift vs Vive vs Hololens but more about the practical uses of it and how you see the technology developing in the medium term -
 say over the next five years. Miniaturization + spec increases are a given, but in terms of the features and functionality, what do you see as key areas and possible killer apps?

**Comment by shanselman** [comment]
Yes, I try to play games a few hours a week. I prefer my Xbox One, but I also have a Nintendo Switch. I also retrogame (I have a dozen from NES up) and build Mame consoles (I have 4 in various sizes) in my spare time.

I have an HTC Vive with the Audio Strap. Roomscale FTW. No hololens - too expensive!

I think that AR will be super useful for education as a visualization tool for stem.

![image](https://user-images.githubusercontent.com/2892/29157213-b3b0e068-7d5a-11e7-91e1-bf151da57bc7.png)
