### ISSUE TITLE
Do you cut your sandwiches in half?

### ISSUE THREAD

**Issue by PierBover** [shanselman/ama#91]

**Comment by styfle** [comment]
And which way?

## Middle

![image](https://user-images.githubusercontent.com/229881/29102632-87e3711c-7c88-11e7-9d3e-8fec010f6c53.png)

## Diagonal 

![image](https://user-images.githubusercontent.com/229881/29102642-9435bf2e-7c88-11e7-8507-bbb78911e59e.png)

**Comment by joshsaintjacque** [comment]
There is a correct answer to this one.

**Comment by shanselman** [comment]
Diagonal of course.

**Comment by PierBover** [comment]
> Diagonal of course

I knew you were a man of reason.
