### ISSUE TITLE
Do you see a future for .Net Core?

### ISSUE THREAD

**Issue by Lidanha** [shanselman/ama#93]
There are many other technologies out there for cross platform technologies on server side and it doesn't seem that .Net Core becomes a trend (at least in Israel). I feel like Microsoft released a good product but it was too late (Much like Windows Phone TMO). 
What do you think?

**Comment by shanselman** [comment]
I absolutely do, otherwise I wouldn't be working on it.

I came to Microsoft 10 years ago to Open Source .NET. We did it.
