### ISSUE TITLE
CS Degree vs. Coding Bootcamps.. thoughts? 

### ISSUE THREAD

**Issue by tdopun** [shanselman/ama#97]
I'm a self taught developer and have been in the industry for roughly 9-10 years. I'm curious on your thoughts regarding: 

1) the increasing number of coding  bootcamps that have risen to popularity over the past couple of years

and 

2) is there ever a case where you would suggest someone not attend a college in pursuit of another option to obtain the knowledge necessary to land a role in our industry?

**Comment by shanselman** [comment]
That's a hard question. I would ask @ladynaggaga to chime in here as well.

I started my first years with no degree, self-taught. Then I went back to school and finished a BS in Software Engineering (which is very practical, not Computer Sciencey) so I can see both sides. As a parent of two sons, I can say that I will recommend that they go to at least 4 years of college/university. I think a LOT happens in those 4 years - not just in classes. There's value in those years of a LOT of people. I realize that neurodiversity could mean that uni isn't for everyone, but if you can make it through, it also shows someone looking at your resume that you'll at least stick with something for 4-6 years.

All that said, there's a lot of value in Bootcamps **if you are motivated**. Saron Yitbarek is a great example. She was pre-med, as I recall, heading to becoming a doctor, and dropped out and decided to do a bootcamp. She told everyone she knew that she was "disappearing for a year" - and she did. She buried herself in a bootcamp and came out the other end an excellent technologist.

My point here is that there's value in both journeys, but you'll only get out what you are capable of putting in.
