### ISSUE TITLE
Do you believe that postgraduate education can improve a dev career significantly?

### ISSUE THREAD

**Issue by malekatwiz** [shanselman/ama#99]
Do you believe that getting a masters degree or even a Phd in computer science or software engineering can really boost up a software developer career?
in two perspectives, 
- knowledge and ability to contribute more to the job
- financially and getting a new job easily

Can't someone self-taught or with a bachelor degree get to the same result?

**Comment by shanselman** [comment]
For me, that would only improve things if I was going into a research-heavy or academic environment. It might open doors but it wouldn't keep them open. 

However, as I get older I realize that if I was going to move out of dev and into more management, that an MBA would like help my career.

If I was moving lower into compiler theory or language design, I could see that a PhD would help me keep up with my peers.

Sorry...this is a "it depends" answer. Hope it helps.
